default_install_hook_types: [pre-commit]
default_stages: [commit, push]
default_language_version:
  python: python3.11
ci:
    autofix_commit_msg: |
        ci(pre-commit): Autofixing commit msg from pre-commit.com hooks
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: 'ci(autoupdate): Autoupdating commit msg'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        files: ^backend/
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.11
        args:
        - --config=backend/pyproject.toml
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args:
        - --settings-path=backend/pyproject.toml
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    -   id: codespell
        additional_dependencies:
        - tomli
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
    -   id: mypy
        args:
        - --config-file=backend/pyproject.toml
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v3.0.1"
  hooks:
    - id: prettier
      files: \.[jt]sx?$
      types_or: [css, javascript]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.46.0"
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
