global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'demo_server'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'demo_server:8002' ]
  - job_name: 'data_requester'
    static_configs:
      - targets: [ 'data_requester:7003' ]
  - job_name: 'data_processor'
    static_configs:
      - targets: [ 'data_processor:7004' ]
  - job_name: 'data_aggregator'
    static_configs:
      - targets: [ 'data_aggregator:7005' ]
  - job_name: 'db_loader'
    static_configs:
      - targets: [ 'db_loader:7006' ]
  - job_name: 'api_gateway'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'api_gateway:8007' ]