"""user - add memo

Revision ID: 982c154a8a36
Revises: 382ab0927111
Create Date: 2024-01-16 00:18:39.274764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982c154a8a36'
down_revision = '382ab0927111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'memo')
    # ### end Alembic commands ###
