version: '3.9'

services:
  app:
    container_name: fsap_app
    build: .
    env_file:
      - .env
      - .secrets
    command: bash -c "
      uvicorn app.main:app
      --log-config ./config.ini
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - .:/home/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    container_name: fsap_db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
      - .secrets
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $SQL_DB -U $SQL_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: fsap_redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    entrypoint: redis-server --appendonly yes

volumes:
  fastapi_postgres_data: {}