version: "3"

services:
  api:
    build: .
    image: event-planner-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.prod

  database:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data:
